### ISSUE TITLE
[LORO-300] Fractional index

### ISSUE THREAD

**Issue by zxch3n** [loro-dev/loro#140]
This enable users to move element easily. We can integrate it into tree node

<sub>[LORO-300](https://linear.app/loro/issue/LORO-300/fractional-index)</sub>

**Comment by joakim** [comment]
Is this feature dropped or just postponed?

My use case requires manual ordering of Tree children. I think fractional indexing could work, as my use case is similar to [Figma's](https://www.figma.com/blog/realtime-editing-of-ordered-sequences/#fractional-indexing).

However, the third drawback they highlight (averaging between two identical indices) needs to be solved without depending on a central server. Could the second conflicting item simply be assigned the average of the indices of the first conflicting item and the next item?

Or is there some other reason for closing this issue as not planned?

If you're not doing fractal indexing, what are the alternatives?

**Comment by zxch3n** [comment]
It's dropped. 

The fractional index suffers from interleaving problems. We will try building a movable list this season that can avoid this problem while remaining efficient. We hope to integrate it into tree as well. 

The other reason we drop it is that the fractional index the solution can be implemented in the application code. It doesn't require special CRDT behaviors(LLW register is enough), so we can already use it with the current movable trees.

**Comment by joakim** [comment]
Fair enough. Interleaving is OK for me, but I see that it can be a problem for others.

My plan B was to implement reordering myself with LWW, like you say. Shouldn't be too hard.

Thanks for the quick answer(s)!
