### ISSUE TITLE
`Loro.fromSnapshot()` does not turn on auto commit

### ISSUE THREAD

**Issue by hyrious** [loro-dev/loro#177]
**Reproduction**

```js
import { Loro } from 'loro-crdt'

let docA = new Loro
let docB = Loro.fromSnapshot(docA.exportSnapshot())

docB.getMap('map').set('a', 1)
// error: Auto commit has not started. The doc is readonly when detached. You should ensure autocommit is on and the doc and the state is attached.
```

https://github.com/loro-dev/loro/blob/089d05e3a09603e249b4717ad8c6ce26335a18f1/crates/loro-wasm/src/lib.rs#L239-L243

Another trivia: currently all internal errors are throwed as string literals in javascript, i.e. `throw "error string"`. However I would prefer using an Error class, i.e. `throw new Error("error string")` which is more usual.

**Comment by zxch3n** [comment]
Thanks!

**Comment by zxch3n** [comment]
Fixed
