### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by ZutJoe** [loro-dev/loro#182]
platform: windows10 22H2

## run `deno task test-wasm` error

`__dirname`, `__filename` is wrong when I run 'deno task test-wasm'

![image](https://github.com/loro-dev/loro/assets/54732130/aa0b6ea7-2c27-4a59-a614-d83f2fb4970b)

after change `__dirname`:

![image](https://github.com/loro-dev/loro/assets/54732130/013253ee-1ae5-46f4-88f1-aab7b25e8137)

## run `deno task test`

can you give me some help with the error?

node version: 16.20.1

![image](https://github.com/loro-dev/loro/assets/54732130/861c95ba-6d38-4a9f-9bac-cd0843b0a67d)

**Comment by Leeeon233** [comment]
@ZutJoe Could you try the branch of this pr #183 ? Does the issue still exist?

**Comment by ZutJoe** [comment]
> @ZutJoe Could you try the branch of this pr #183 ? Does the issue still exist?

fix

can you give me some tips on the second question

**Comment by ZutJoe** [comment]
> @ZutJoe It seems to be a issue with `napi` on the windows platform. [napi-rs/napi-rs#1405](https://github.com/napi-rs/napi-rs/issues/1405)

ok, thanks
