### ISSUE TITLE
Feature Request: Realtime replay

### ISSUE THREAD

**Issue by JasCodes** [loro-dev/loro#186]
hi @zxch3n  @Leeeon233 
Great work!! Much appreciated.

If I want to replay events with as something like a video, can to update the clock with client clock to achieve this?

Jas

**Comment by Leeeon233** [comment]
Could you provide a more detailed description of your request?  I'm not clear on what you mean by 'replay events'.

**Comment by JasCodes** [comment]
Just wanted to replay like video player with x times playback speed. Think of it as light weight video capture.

**Comment by Leeeon233** [comment]
We support [time travel](https://loro.dev/docs/tutorial/time_travel) feature, which allows you to implement `reply events` by starting from the first version and constantly checking out to the latest version.

Maybe something like
```ts
const doc = new Loro();
doc.subscribe((_e)=>{
      // handle the event
});
/*
    Perform your operations here
*/

// all versions
const versions = [......];
for (const version of versions){
    doc.checkout(version);
}

```
**Note**:  In a distributed system, versions are not arranged linearly. You may need to organize these versions according to your specific needs.
