### ISSUE TITLE
Seeking Community Feedback on Integrating 'Prelim' Feature

### ISSUE THREAD

**Issue by Leeeon233** [loro-dev/loro#216]
This issue aims to gather community feedback regarding the potential inclusion of a `Prelim` feature, similar to what is offered in `Yrs`. If you find this feature necessary and useful, please respond with an emoji to let us know. It will be considered before the stable v1.0 version is released.

The `Prelim` feature provides a set of native js data structures for `Text`/`Map`/`List` etc., which can later be integrated into `Loro` CRDTs at an appropriate time. Below is a simple example of how it works:

```js
// use prelim type
const prelimText = new PrelimText("foo");
const prelimList = new PrelimList([1, "a"]);

// then you create the Loro doc
const doc = new Loro();
const map = doc.getMap("map");
map.set("text", prelimText);
map.set("list", prelimList);
doc.commit();
console.log(map.toJson());   // {"text": "foo", "list": [1, "a"]}
```

**Comment by zxhd863943427** [comment]
That is, first create a JavaScript structure, and then convert it directly to Loro? This is a good feature, and the reason I use syncedStore instead of yjs is that syncedStore provides such functionality.
