### ISSUE TITLE
Feature Request: Property Graph Model

### ISSUE THREAD

**Issue by poelzi** [loro-dev/loro#217]
I'm a huge fan of [logseq](http://logseq.com), it is life changing software. But the architecture is slow and clunky.

I think loro would be perfect fit to building a new iteration of it.
The required model would have following properties:

* In logseq you have pages and each page contains n blocks.
 * The page itself has metadata as well as all blocks.
 * Metadata are attributes that are auto generated, like last update, uuid, ...
 * Also user defined attributes, which are just lines with
```name:: value```
somewhere in the block.
 * nice to have: binary attachment to blocks
    * use a hash based separate blob store and only reference those ids
 *  Block can have links to other blocks and pages, awareness of that and proper merging would be awesome

The content of a block is just markdown with some more syntax.
Some attributes, that are hidden in the UI need to be updated depending on definition. Like the update time.

I think a model like this that can be configured by the user, is a super flexible way to nearly describe any app.
Directed property graphs can store most data structures very efficiently.

**Comment by zxch3n** [comment]
Is it sufficient to model Logseq by treating each page as a single document? Each document can have multiple containers like blocks and each block can contains multiple attributes. The requirements you listed can be satisfied with this model except the last one. The operations on links between the blocks and pages cannot be reliably merged if it involves concurrent operations like:

- Renaming page, which updates all [[PAGE_NAME]] to [[NEW_PAGE_NAME]]. If there is a concurrent edit create a new  [[PAGE_NAME]] link, this link will not be updated.
- Refreshing all block id. Concurrent edits that create new links to the blocks will be invalidated.

**Comment by poelzi** [comment]
This is good to read: [start here](https://docs.logseq.com/#/page/start%20here)
Logseq graph is more a unity spanning multiple files in the default implementation.
If something like renames would provide hooks to provide additional functionality, rename could be made nicely.
For example, when a page is renamed, the hook could search all other pages for links and rename those. This would be then part of the rename transaction if possible.
Of course, some concurrent actions can never be resolved properly. But the current solution to try to sync as much as possible is just not that nice on the long run.
I use syncthing to sync which is one of the best solutions but still get some conflicts now and then.
