### ISSUE TITLE
[LORO-371] The behavior of richtext's `applyDelta()` is not entirely correct

### ISSUE THREAD

**Issue by Leeeon233** [loro-dev/loro#225]
```ts
const doc = new Loro();
const text = doc.getText("text");
const doc2 = new Loro();
const text2 = doc2.getText("text");
text.subscribe(doc, (event)=>{
  const e = event.diff as TextDiff;
  text2.applyDelta(e.diff);
});
text.insert(0, "foo");
text.mark({start: 0, end: 3, expand: "none"}, "link", true);
// doc.commit();   // multi delta
text.insert(3, "baz");
doc.commit();
await new Promise((r) => setTimeout(r, 1));
expect(text2.toDelta()).toStrictEqual([ { insert: 'foo', attributes: { link: true } }, { insert: 'baz' } ]);
```

If uncomment first `doc.commit()`, the result will be wrong

<sub>From [SyncLinear.com](https://synclinear.com) | [LORO-371](https://linear.app/loro/issue/LORO-371/the-behavior-of-richtexts-applydelta-is-not-entirely-correct)</sub>

**Comment by zxch3n** [comment]
To make this work, it would need users to configure a mapping from the name of the style to its expanding behavior (or TextStyleInfoFlag specifically). Currently, it uses the bold-like behavior by default.
