### ISSUE TITLE
Missing characters in time travel video

### ISSUE THREAD

**Issue by joakim** [loro-dev/loro#230]
When pausing the time travel video in the [readme](https://github.com/loro-dev/loro#advanced-features-in-loro), I noticed lots of missing characters at several points on the timeline. Is that from an older buggier version, or is it still an issue?

That little worry aside, Loro looks really promising! You've got an early adopter here.

**Comment by zxch3n** [comment]
Thanks for your interest! Yes, it’s from a more buggy version. We’ve fixed a few bugs related to time travel and added new fuzzing tests to cover more corner cases caused by the combination of time travel and collaboration.
