### ISSUE TITLE
Loro and FinalizationRegistry

### ISSUE THREAD

**Issue by mikecann** [loro-dev/loro#248]
Hi,

I am experimenting around with Loro and [Convex](https://convex.dev) bun unfortunately I ran into an issue:

```
✖ Error: Unable to push deployment config to https://kindly-elephant-254.convex.cloud
400 Bad Request: InvalidModules: Hit an error while pushing:
Loading the pushed modules encountered the following
    error:
Failed to analyze auth.js: Uncaught ReferenceError: FinalizationRegistry is not defined
    at <anonymous> (../node_modules/loro-wasm/bundler/loro_wasm_bg.js:209:9)
```

When I [raised this with convex](https://discord.com/channels/1019350475847499849/1197172506084265984/1197172506084265984) they told me:

> Wasm should work in general. The error seems to be about FinalizationRegistry https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry
which Convex runtime does not support because it is nondeterminstic (it relies on knowing when garbage collection runs) so it messes with query subscriptions and mutation conflict detection which rely on determinism. I don't know why Loro uses FinalizationRegistry (it shouldn't be required to use wasm) so it may be possible to avoid the usage or hack around it if not.

So my question, it it possible to remove the use of FinalizationRegistry from Loro? What is it used for currently?

Cheers

**Comment by Leeeon233** [comment]
We employ the [`weak references`](https://rustwasm.github.io/wasm-bindgen/reference/weak-references.html) feature of `wasm-bindgen` to avoid the need for developers to manually call `free()` for memory release. 

If your environment does not support `FinalizationRegistry`, you might need to remove the `--weak-refs` flag from the `build.ts` script in `loro-wasm`, and manually release memory for objects when they are no longer needed.

**Comment by mikecann** [comment]
Okay thanks
