### ISSUE TITLE
Calling `setPeerId` with anything but `number` crashes

### ISSUE THREAD

**Issue by BeeeQueue** [loro-dev/loro#305]
Like the title says, `new Loro().setPeerId("hello")` immediately crashes for me.

![image](https://github.com/loro-dev/loro/assets/472500/7d2089a6-7413-4931-9f8a-096cc2b1e5be)

Using loro with `vite@5.2.7` and `vite-plugin-wasm@3.3.0`

**Comment by Leeeon233** [comment]
We use `u64` as `PeerId` in rust. So the input is a type convertible to `u64`, such as `number`, `bigint` or `number string`.

**Comment by zxch3n** [comment]
I'll update the doc and error messages to address that

**Comment by zxch3n** [comment]
The typing of PeerID is string now, which needs to be clarified. I'll change it to `${number}`;
