### ISSUE TITLE
Consider a larger peer ID

### ISSUE THREAD

**Issue by dgllghr** [loro-dev/loro#376]
Currently the peer ID is limited to a `u64`. To avoid peer ID collisions with a large number of peers (or needing some kind of central coordination for peer IDs), I would like to use UUIDs as peer IDs. Please consider increasing the size of the peer ID to `u128` or `[u8; 16]`.

**Comment by zxch3n** [comment]
Emm I think by using u64, the possibility of collision for a single CRDT document is low enough. The possibility of collision should be negligible even if there are 1M peers.
