### ISSUE TITLE
`LoroMap::len` and `LoroMap::is_empty` inconsistency

### ISSUE THREAD

**Issue by dileping** [loro-dev/loro#397]
`LoroMap::len` and `LoroMap::is_empty` don't report the current state correctly after a `delete` operation. Here is a short snippet to reproduce:

```rust
pub fn len_bug() -> anyhow::Result<()> {
    let doc = LoroDoc::new();
    let map = doc.get_map("map");

    assert!(map.is_empty());

    map.insert("leaf", 42i64)?;

    assert_eq!(map.len(), 1);

    map.delete("leaf")?;

    assert_eq!(map.len(), 0);

    Ok(())
}
```

**Comment by zxch3n** [comment]
Thanks for reporting this. Internally, we treat removal as setting the entry to None, so it has this behavior. But, yeah, it makes more sense to treat the len as 0 in this case.

**Comment by dileping** [comment]
@zxch3n Thanks for the fast reply. Please let me know if you need any more input.

**Comment by siyou** [comment]
#402
