### ISSUE TITLE
Issues with lldb breakpoints

### ISSUE THREAD

**Issue by sinkingsugar** [loro-dev/loro#412]
I would love to use Loro as a replacement for yrs but I have issues debugging any code when including this crate. 
Basically it triggers `illegal hardware instruction` on macos (arm) lldb every time a breakpoint is hit.

I tested even with this repository purely and setting a breakpoint on a test, same result. I suspect some dependency is doing something funny.
I will try to `cargo tree` and see if I can figure more. But I wonder if anyone else experienced something similar?

Tested with:
nightly-2024-05-01-aarch64-apple-darwin (default)
and
stable-aarch64-apple-darwin updated - rustc 1.80.0 (051478957 2024-07-21) (from rustc 1.79.0 (129f3b996 2024-06-10))

**Comment by sinkingsugar** [comment]
Update: totally ignoring the crate `loro` and using directly `loro-internal` fixed the issue.
It is strange cos `loro` seems just a small wrapper on top of internal.

**Comment by zxch3n** [comment]
This is a weird issue. I can reproduce it on my M1 machine. After making the following change, it works
![CleanShot 2024-07-29 at 11 48 00@2x](https://github.com/user-attachments/assets/4782cdd4-1111-4e9a-991a-57e1332539a3)

I guess it's related to how the debugger displays info, and the Rust compiler has some optimization trick that does not work well with it. I'll patch a workaround for debugging.

**Comment by sinkingsugar** [comment]
> This is a weird issue. I can reproduce it on my M1 machine. After making the following change, it works ![CleanShot 2024-07-29 at 11 48 00@2x](https://private-user-images.githubusercontent.com/18425020/352908485-4782cdd4-1111-4e9a-991a-57e1332539a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzI3ODMsIm5iZiI6MTcyMjIzMjQ4MywicGF0aCI6Ii8xODQyNTAyMC8zNTI5MDg0ODUtNDc4MmNkZDQtMTExMS00ZTlhLTk5MWEtNTdlMTMzMjUzOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA1NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZmRkY2E1ODBjZTVmYjBmMDVmNWQ2MTU1NzEyZTAyMWQwNzk1NDBiZGMxMzZmNzNkOThlZTIzMDIyZDY1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GUadfFyoGqEr3dZgdU27MxY1Fg8t8sytOFodyxqxEi0)
> 
> I guess it's related to how the debugger displays info, and the Rust compiler has some optimization trick that does not work well with it. I'll patch a workaround for debugging.

Oh wow snap, I was kinda suspecting that `transparent` but did not try! Interesting. Sounds like a rust compiler issue indeed. Nice work finding it!
