### ISSUE TITLE
History management in Loro

### ISSUE THREAD

**Issue by dileping** [loro-dev/loro#416]
Hi guys,

Have you explored something related to history truncation/management/garbage collection for Loro? Maybe something like this: [antimatter](https://braid.org/antimatter)?

What do you think about the topic? Is Antimatter a viable option, or do you have something better in mind?

Thanks,
Daniel

**Comment by zxch3n** [comment]
Yes. Based on the REG algorithm, we can offer a straightforward API to trim the history by timestamp. For example, we can allow users to omit all the history edits that happened one month ago and put them in cold storage. So you may have the best properties of both worlds.

Antimatter doesn't suit us. It involves a lot of bookkeeping, and I think it's very hard to tell whether a peer is going to make new edits after it goes offline in a real-world scenario. 

We are still working on it. Once it's done, I'll write a document to discuss the details.

**Comment by dileping** [comment]
@zxch3n Thanks for your fast reply! What you described sounds very useful in real-world scenarios. Do you have any plans for the release date?

**Comment by zxch3n** [comment]
Hopefully this month!

**Comment by dileping** [comment]
@zxch3n Very exciting! I'm looking forward to it and would love to test it.
