### ISSUE TITLE
Is it possible to sync updates without loading the document into memory?

### ISSUE THREAD

**Issue by vadolasi** [loro-dev/loro#502]
As Yjs allows: https://docs.yjs.dev/api/document-updates#alternative-update-api

I would like this feature to save each update to the database as soon as it is received on the server.

**Comment by zxch3n** [comment]
Yes, by using the detached mode. The following code will not load the document state into the memory:

```js
let doc = new LoroDoc();
doc.detach();
doc.import(remoteBytes);
```
