### ISSUE TITLE
Request: Make all Git-like features optional

### ISSUE THREAD

**Issue by diversable** [loro-dev/loro#563]
First off, congrats on the 1.0 release! Great work!
 
I would humbly request, however, that you seriously consider making all git-like features of the Loro lib optional - Git itself, with its 3-way-merge algorithm, is fundamentally broken as a tool for merging edits of different branches (mathematically speaking). That is, it sometimes gets things 'wrong' resulting in shuffling lines around and generally making resolving merge conflicts harder than it absolutely has to be (git rerere, anyone?).

For more about the issues with the Git merge algorithm, and for an alternative implementation of a  Version Control System (VCS) that is mathematically sound, check out the Pijul VCS (cf. https://pijul.org/). 

I understand that the vast majority of users are attached to git, since it came about when a lot of other VCS tools sucked and git legitimately solved some issues, but just because it was better than the tools we had 20 years ago doesn't mean that 'Git is the end of innovation in VCS tools'.

At the very least, please allow Loro lib users to avoid any Git-like implementations of version control so that they can manually build in better solutions, such as are implemented in Pijul VCS. 

Thank you for your consideration.

Sincerely,

Daniel

**Comment by zxch3n** [comment]
Thanks!

In our blog, Git was mentioned as an analogy to help people better understand, but the underlying working principles are quite different from Git. For example, when we merge, it's done through automatic CRDT merging (2-way-merge where users don't need additional commits), rather than using Git's 3-way-merge approach. 

From a theoretical perspective, Loro is actually more similar to Pijul - we essentially store patches as well, and we also have Pijul's Change commutation and Associativity. 

I'm not sure if this addresses the Git-related issues you pointed out.

**Comment by diversable** [comment]
> Thanks!
> 
> In our blog, Git was mentioned as an analogy to help people better understand, but the underlying working principles are quite different from Git. For example, when we merge, it's done through automatic CRDT merging (2-way-merge where users don't need additional commits), rather than using Git's 3-way-merge approach.
> 
> From a theoretical perspective, Loro is actually more similar to Pijul - we essentially store patches as well, and we also have Pijul's Change commutation and Associativity.
> 
> I'm not sure if this addresses the Git-related issues you pointed out.

Thanks for your response! 

I guess I spoke a little too quickly in response to your blog post - I didn't get that the git reference was just an analogy rather than 'an intention to integrate Loro with Git somehow, at some point during Loro's future development'. 

Thank you for clarifying things for me. I appreciate you taking the time to explain that.

Now that that's been resolved.. I would be interested to hear what you have on the roadmap for Loro now that you've released v.1.0 - it might be a good topic for a future blog post ;)

Cheers!

**Comment by zxch3n** [comment]
We do hope to find a way to smoothly integrate Loro into a Git-based workspace, which would allow us to seamlessly add capabilities like real-time rich text collaboration on Git repositories, making it possible to integrate more powerful and user-friendly tools. However, this integration won't change Loro's conflict resolution logic - it essentially remains a different VCS from Git, so we're still uncertain about how feasible this would be.

The other directions we will explore include:

- Real-time collaborative version control
- Better integration with existing tools
- Making Loro application deployment more convenient
- Inspector
- End-to-end encryption
