### ISSUE TITLE
Include `origin` and `commitMessage` in the UndoManager's onPush and onPop

### ISSUE THREAD

**Issue by zxch3n** [loro-dev/loro#584]

**Comment by raymonddaikon** [comment]
I'm assuming adding the actual change event would be too much overhead 🤔? Although I suspect for most cases struturing the commit and origin should be enough to grab the correct value, I'm just thinking through cases that might need previousValue in `onPush`

**Comment by zxch3n** [comment]
@raymonddaikon We don't need to persist in the actual change event. We can expose the messages in onPush; then, users can choose what to store by returning the value. The interface of onPop doesn't need changing.

**Comment by raymonddaikon** [comment]
But what about passing the change event to onPush, might be easier to grab the value instead of 
`
// Assuming commit is something like 'name-change'
onPush: (origin, commit, isUndo, counterRange) => {
       switch(commit) {
       case 'name-change': { 
            return { value: loroDoc.get('name').toString(), cursors: [] }
       }
     default: {
         return { value: null, cursors: [] }
    }
  })`

**Comment by zxch3n** [comment]
Got it. Yeah, we can do that.
